name: Android CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone submosule
        run: git submodule update --init --recursive
      - name: Set up SDK and NDK
        run: |
          yes | sudo $ANDROID_HOME/tools/bin/sdkmanager ndk-bundle > /dev/null
          LP=./local.properties
          rm -rf $LP
          echo "sdk.dir=$ANDROID_HOME" >> $LP
          echo "ndk.dir=$ANDROID_HOME/ndk-bundle" >> $LP
      - name: Build app
        run: |
          ./gradlew :app:assembleDebug
      - name: Configure SSH key
        env:
          SSH_PRK: ${{ secrets.SSH_PRK }}
        run: |
          if [ ! -d ~/.ssh ]; then
              mkdir ~/.ssh
          fi
          ssh-keyscan gitee.com 2> /dev/null >> ~/.ssh/known_hosts
          echo $SSH_PRK | base64 -d > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      - name: Upload apk to Gitee
        run: |
          git clone git@gitee.com:bczhc/store
          cd store
          if [ ! -d apks ]; then
              mkdir apks
          fi
          cd apks
          cp -v ../../app/build/outputs/apk/debug/app-debug.apk some-tools.apk
          git config --global user.email "bczhc0@126.com"
          git config --global user.name "bczhc"
          git add some-tools.apk
          git commit -m "Upload apk by GitHub Action on $(date)"
          git push origin master -f
          cd ../..
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
