name: Android CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone submosule
        run: git submodule update --init --recursive
      - name: setup NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager
          echo "export ANDROID_NDK_HOME=${ANDROID_HOME}/ndk-bundle" >> ~/.profile
      - name: Build app
        run: |
          source ~/.profile
          ./gradlew :app:assembleDebug
      - name: Configure SSH key
        env:
          SSH_PRK: ${{ secrets.SSH_PRK }}
        run: |
          if [ ! -d ~/.ssh ]; then
              mkdir ~/.ssh
          fi
          ssh-keyscan gitee.com 2> /dev/null >> ~/.ssh/known_hosts
          echo $SSH_PRK | base64 -d > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      - name: Upload apk to Gitee
        run: |
          git clone git@gitee.com:bczhc/store
          cd store
          if [ ! -d apks ]; then
              mkdir apks
          fi
          cd apks
          cp -v ../../app/build/outputs/apk/debug/app-debug.apk some-tools.apk
          cd ../..
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
